import type { CategorySlug, Product } from "./types";

const SIZES_BABY = ["50-60", "70", "80", "90", "95"];
const SIZES_SMALL = ["70", "80", "90"];

export const products: Product[] = [
  {
    id: "romper-cloud",
    name: { ja: "くも柄 長袖ロンパース", ko: "구름무늬 긴팔 롬퍼" },
    brand: "hinata",
    category: "rompers",
    price: 2980,
    listPrice: 3800,
    colors: ["#e9dfd2", "#dfe5d9", "#f4e2df"],
    sizes: SIZES_BABY,
    season: "aw",
    isNew: true,
    isBest: true,
    soldOut: false,
    rating: 4.8,
    reviewCount: 132,
    description: {
      ja: "やわらかな綿100%。肌に触れる部分にもこだわった定番ロンパースです。",
      ko: "부드러운 면 100%. 피부에 닿는 부분까지 신경 쓴 스테디셀러 롬퍼예요.",
    },
  },
  {
    id: "romper-bear",
    name: { ja: "くまさん 半袖ロンパース", ko: "곰돌이 반팔 롬퍼" },
    brand: "hinata",
    category: "rompers",
    price: 2480,
    listPrice: 2480,
    colors: ["#f4e2df", "#e9dfd2"],
    sizes: SIZES_BABY,
    season: "ss",
    isNew: false,
    isBest: true,
    soldOut: false,
    rating: 4.7,
    reviewCount: 210,
    description: {
      ja: "夏でも快適なさらり素材。前開きでお着替えらくらく。",
      ko: "여름에도 쾌적한 산뜻한 소재. 앞트임으로 갈아입히기 편해요.",
    },
  },
  {
    id: "romper-knit",
    name: { ja: "ニット風 足つきカバーオール", ko: "니트풍 발싸개 커버올" },
    brand: "mori",
    category: "rompers",
    price: 4200,
    listPrice: 5200,
    colors: ["#dfe5d9", "#e9dfd2", "#d9d0c4"],
    sizes: ["50-60", "70", "80"],
    season: "aw",
    isNew: true,
    isBest: false,
    soldOut: false,
    rating: 4.9,
    reviewCount: 58,
    description: {
      ja: "あたたかいニット調。足先まで包んで寒い季節も安心。",
      ko: "따뜻한 니트 질감. 발끝까지 감싸 추운 계절에도 안심이에요.",
    },
  },
  {
    id: "inner-organic-2set",
    name: { ja: "オーガニック肌着 2枚セット", ko: "오가닉 내의 2매 세트" },
    brand: "mori",
    category: "innerwear",
    price: 1980,
    listPrice: 2600,
    colors: ["#fbf9f6", "#f1ebe3"],
    sizes: SIZES_BABY,
    season: "all",
    isNew: false,
    isBest: true,
    soldOut: false,
    rating: 4.9,
    reviewCount: 421,
    description: {
      ja: "オーガニックコットン使用。デリケートな肌にやさしい定番セット。",
      ko: "오가닉 코튼 사용. 예민한 피부에 순한 스테디 세트예요.",
    },
  },
  {
    id: "inner-short",
    name: { ja: "短肌着 3枚組", ko: "배냇저고리 3매 세트" },
    brand: "hinata",
    category: "innerwear",
    price: 1580,
    listPrice: 1580,
    colors: ["#fbf9f6", "#f4e2df", "#dfe5d9"],
    sizes: ["50-60", "70"],
    season: "all",
    isNew: false,
    isBest: false,
    soldOut: false,
    rating: 4.6,
    reviewCount: 176,
    description: {
      ja: "新生児にちょうどいい短肌着。汗をよく吸う綿100%。",
      ko: "신생아에게 딱 좋은 배냇저고리. 땀 흡수가 좋은 면 100%.",
    },
  },
  {
    id: "inner-longsleeve",
    name: { ja: "コンビ肌着 長袖", ko: "콤비 내의 긴팔" },
    brand: "mori",
    category: "innerwear",
    price: 1280,
    listPrice: 1680,
    colors: ["#f1ebe3", "#dfe5d9"],
    sizes: SIZES_BABY,
    season: "aw",
    isNew: true,
    isBest: false,
    soldOut: false,
    rating: 4.5,
    reviewCount: 64,
    description: {
      ja: "はだけにくいコンビタイプ。動きが活発な赤ちゃんにも。",
      ko: "잘 벌어지지 않는 콤비 타입. 활발한 아기에게도 좋아요.",
    },
  },
  {
    id: "top-frill",
    name: { ja: "フリル袖 トレーナー", ko: "프릴 소매 맨투맨" },
    brand: "petit",
    category: "tops",
    price: 2680,
    listPrice: 3200,
    colors: ["#f4e2df", "#e9dfd2"],
    sizes: SIZES_SMALL,
    season: "aw",
    isNew: true,
    isBest: true,
    soldOut: false,
    rating: 4.7,
    reviewCount: 89,
    description: {
      ja: "さりげないフリルがかわいい裏起毛トレーナー。",
      ko: "은은한 프릴이 사랑스러운 기모 맨투맨이에요.",
    },
  },
  {
    id: "top-stripe-tee",
    name: { ja: "ボーダー 半袖Tシャツ", ko: "스트라이프 반팔 티셔츠" },
    brand: "petit",
    category: "tops",
    price: 1480,
    listPrice: 1480,
    colors: ["#dfe5d9", "#e9dfd2", "#f4e2df"],
    sizes: SIZES_SMALL,
    season: "ss",
    isNew: false,
    isBest: false,
    soldOut: true,
    rating: 4.4,
    reviewCount: 143,
    description: {
      ja: "コーデしやすい定番ボーダー。何枚あっても便利。",
      ko: "코디하기 쉬운 기본 스트라이프. 여러 장 있어도 좋아요.",
    },
  },
  {
    id: "bottom-baggy",
    name: { ja: "ゆるっと モンキーパンツ", ko: "루즈핏 몽키 팬츠" },
    brand: "petit",
    category: "bottoms",
    price: 1980,
    listPrice: 2400,
    colors: ["#e9dfd2", "#d9d0c4", "#dfe5d9"],
    sizes: SIZES_SMALL,
    season: "all",
    isNew: false,
    isBest: true,
    soldOut: false,
    rating: 4.8,
    reviewCount: 201,
    description: {
      ja: "おむつ姿もすっぽり。伸びる素材で動きやすい。",
      ko: "기저귀도 쏙 감싸는 신축성 좋은 소재로 움직임이 편해요.",
    },
  },
  {
    id: "bottom-leggings",
    name: { ja: "のびのび レギンス", ko: "쭉쭉 레깅스" },
    brand: "mori",
    category: "bottoms",
    price: 1180,
    listPrice: 1180,
    colors: ["#d9d0c4", "#dfe5d9", "#f4e2df"],
    sizes: SIZES_BABY,
    season: "all",
    isNew: true,
    isBest: false,
    soldOut: false,
    rating: 4.6,
    reviewCount: 97,
    description: {
      ja: "重ね着に大活躍。やわらか裏地でチクチクしない。",
      ko: "레이어드에 딱. 부드러운 안감으로 까슬거리지 않아요.",
    },
  },
  {
    id: "outer-fleece",
    name: { ja: "もこもこ フリースジャケット", ko: "몽실 플리스 자켓" },
    brand: "mori",
    category: "outer",
    price: 3980,
    listPrice: 4800,
    colors: ["#e9dfd2", "#dfe5d9"],
    sizes: SIZES_SMALL,
    season: "aw",
    isNew: true,
    isBest: true,
    soldOut: false,
    rating: 4.9,
    reviewCount: 76,
    description: {
      ja: "軽くてあたたか。お出かけにも羽織りやすい一枚。",
      ko: "가볍고 따뜻해요. 외출할 때 걸치기 좋은 한 벌이에요.",
    },
  },
  {
    id: "outer-vest",
    name: { ja: "リバーシブル ダウンベスト", ko: "리버시블 다운 베스트" },
    brand: "petit",
    category: "outer",
    price: 4600,
    listPrice: 4600,
    colors: ["#d9d0c4", "#dfe5d9", "#f4e2df"],
    sizes: SIZES_SMALL,
    season: "aw",
    isNew: false,
    isBest: false,
    soldOut: false,
    rating: 4.7,
    reviewCount: 52,
    description: {
      ja: "2wayで長く使える。体温調節にも便利なベスト。",
      ko: "2way로 오래 쓰는 베스트. 체온 조절에도 편리해요.",
    },
  },
  {
    id: "acc-socks-3set",
    name: { ja: "くしゅくしゅ ソックス 3足", ko: "쭈글 양말 3켤레" },
    brand: "petit",
    category: "accessories",
    price: 980,
    listPrice: 1200,
    colors: ["#f4e2df", "#dfe5d9", "#e9dfd2"],
    sizes: ["70", "80"],
    season: "all",
    isNew: false,
    isBest: true,
    soldOut: false,
    rating: 4.5,
    reviewCount: 268,
    description: {
      ja: "脱げにくい設計。パステルカラーの3足セット。",
      ko: "잘 벗겨지지 않는 설계. 파스텔 컬러 3켤레 세트예요.",
    },
  },
  {
    id: "acc-hat",
    name: { ja: "つば付き ベビーハット", ko: "챙 달린 아기 모자" },
    brand: "hinata",
    category: "accessories",
    price: 1680,
    listPrice: 1680,
    colors: ["#e9dfd2", "#dfe5d9"],
    sizes: ["70", "80", "90"],
    season: "ss",
    isNew: true,
    isBest: false,
    soldOut: false,
    rating: 4.6,
    reviewCount: 41,
    description: {
      ja: "日差しからやさしく守る、あご紐付きの帽子。",
      ko: "햇빛을 부드럽게 막아주는 턱끈 달린 모자예요.",
    },
  },
  {
    id: "acc-bib",
    name: { ja: "スタイ 4枚セット", ko: "턱받이 4매 세트" },
    brand: "mori",
    category: "accessories",
    price: 1380,
    listPrice: 1800,
    colors: ["#dfe5d9", "#f4e2df", "#e9dfd2", "#d9d0c4"],
    sizes: ["50-60"],
    season: "all",
    isNew: false,
    isBest: false,
    soldOut: false,
    rating: 4.8,
    reviewCount: 189,
    description: {
      ja: "よだれをしっかり吸収。かわいい4色セット。",
      ko: "침을 잘 흡수해요. 사랑스러운 4색 세트.",
    },
  },
  {
    id: "gift-newborn-box",
    name: { ja: "出産祝い ギフトボックス", ko: "출산 축하 기프트 박스" },
    brand: "mori",
    category: "gift",
    price: 6800,
    listPrice: 8500,
    colors: ["#f4e2df", "#dfe5d9"],
    sizes: ["50-60", "70"],
    season: "all",
    isNew: true,
    isBest: true,
    soldOut: false,
    rating: 5.0,
    reviewCount: 63,
    description: {
      ja: "ロンパース・スタイ・ソックスを詰めた人気ギフト。ラッピング無料。",
      ko: "롬퍼·턱받이·양말을 담은 인기 선물세트. 포장 무료예요.",
    },
  },
  {
    id: "gift-fukubukuro",
    name: { ja: "季節の福袋 5点セット", ko: "시즌 럭키백 5종 세트" },
    brand: "hinata",
    category: "gift",
    price: 5000,
    listPrice: 9800,
    colors: ["#e9dfd2", "#dfe5d9", "#f4e2df"],
    sizes: SIZES_SMALL,
    season: "all",
    isNew: true,
    isBest: false,
    soldOut: false,
    rating: 4.7,
    reviewCount: 128,
    description: {
      ja: "何が届くかお楽しみ。おトクな5点入りの福袋です。",
      ko: "무엇이 올지 기대되는, 알찬 5종 구성 럭키백이에요.",
    },
  },
];

export const getProduct = (id: string): Product | undefined =>
  products.find((p) => p.id === id);

export const getByCategory = (slug: CategorySlug): Product[] =>
  products.filter((p) => p.category === slug);

export const bestProducts = (): Product[] => products.filter((p) => p.isBest);

export const newProducts = (): Product[] => products.filter((p) => p.isNew);

export const searchProducts = (query: string): Product[] => {
  const q = query.trim().toLowerCase();
  if (!q) {
    return [];
  }
  return products.filter((p) => matchesQuery(p, q));
};

const matchesQuery = (p: Product, q: string): boolean => {
  const haystack = `${p.name.ja} ${p.name.ko} ${p.brand}`.toLowerCase();
  return haystack.includes(q);
};
